apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80  #only for documentation purpose like EXPOSE 80 in Dockerfile
  - name: sidecar
    image: almalinux:8
    command: ["sleep", "3600"]