apiVersion: v1
kind: Pod
metadata:
  name: labels
  namespace: roboshop
  labels:
    project: roboshop-demo
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80  #only for documentation purpose like EXPOSE 80 in Dockerfile
