apiVersion: v1
kind: Pod
metadata:
  name: annotations
  namespace: roboshop
  #no limit on the number of annotations, but it is recommended to keep it less than 10
  #external tools can use annotations to store and retrieve metadata about the object
  annotations:
    description: "This is a sample nginx pod"
    owner: "Mahesh" 
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80  #only for documentation purpose like EXPOSE 80 in Dockerfile
