apiVersion: v1
kind: Service
metadata:
  name: access-replicasetpods
  namespace: roboshop
spec:
  type: NodePort
  selector:
    project: roboshop-demo
    infrastructure: eks
    environment: dev
    tier: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30080