apiVersion: apps/v1
kind: Deployment
metadata:
  name: scutiarts-deployment
  namespace: roboshop
  labels:
      project: roboshop-demo
      infrastructure: eks
      environment: dev
      tier: frontend
  annotations:
    kubernetes.io/change-cause: "scutiarts"
spec:
  replicas: 3
  selector:
    matchLabels:
      project: roboshop-demo
      infrastructure: eks
      environment: dev
      tier: frontend
  template:
    metadata:
      labels:
        project: roboshop-demo
        infrastructure: eks
        environment: dev
        tier: frontend
    spec:
      containers:
      - name: scutiarts
        image: akkimahesh/scutiarts:latest
        ports:
        - containerPort: 80
