apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: roboshop
  labels:
      project: roboshop-demo
      infrastructure: eks
      environment: dev
      tier: frontend
  annotations:
    kubernetes.io/change-cause: "nginx:stable-trixie-perl"
spec:
  replicas: 3
  selector:
    matchLabels:
      project: roboshop-demo
      infrastructure: eks
      environment: dev
      tier: frontend
  template:
    metadata:
      labels:
        project: roboshop-demo
        infrastructure: eks
        environment: dev
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:stable-trixie-perl
        ports:
        - containerPort: 80
